version: '3.8'

services:
  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    container_name: agriculture-ai
    volumes:
      - ./ai-service:/app

  spring-backend:
    build: ./spring-backend
    ports:
      - "8080:8080"
    container_name: agriculture-backend
    environment:
      - PYTHON_SERVICE_URL=http://ai-service:8000
      - APP_API_KEY=1234
    depends_on:
      - ai-service
